version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "=== 파일 구조 확인 시작 ==="
      - ls -R
      - echo "=== 파일 구조 확인 끝 ==="
      - cd frontend/src
      - npm cache clean --force
      - rm -rf node_modules package-lock.json
      - npm install -g @angular/cli@17
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - cd backend/src
      - ng build -c production
      - echo "Build completed."
    finally:
      - echo This is the finally block execution!
artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'
cache:
  paths:
    - node_modules/**/* 
