version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend/src
      - npm install

  build:
    commands:
      - ng test --no-watch --no-progress --browsers=ChromeHeadlessCI 
